# --------------------------------------
# Hexo Butterfly Theme Configuration
# If you have any questions, please refer to the documentation
# Chinese: https://butterfly.js.org/
# English: https://butterfly.js.org/en/
# --------------------------------------

# --------------------------------------
# Navigation Settings
# --------------------------------------

nav:
  # Navigation bar logo image
  logo:
  display_title: true
  # Whether to fix navigation bar
  fixed: false

menu:
  é¦–é¡µ: / || fas fa-home
  é¡µé¢||fas fa-compass:
    å½’æ¡£: /archives/ || fas fa-archive
    æ ‡ç­¾: /tags/ || fas fa-tags
    åˆ†ç±»: /categories/ || fas fa-folder-open
    å›¾åº“: /Gallery/ || fas fa-images
    è¯´è¯´: /talking/ || fas fa-comment-dots
    ç¤ºä¾‹: /link/ || fas fa-thumbs-up
  æ–‡æ¡£||fas fa-book:
    ðŸš€ å¿«é€Ÿå¼€å§‹: /posts/21cfbf15/
    ðŸ“‘ ä¸»é¢˜é¡µé¢: /posts/dc584b87/
    ðŸ›  ä¸»é¡Œé…ç½®: /posts/4aa8abbe/
    âš”ï¸ æ ‡ç­¾å¤–æŒ‚: /posts/ceeb73f/
    â“ ä¸»é¡Œé—®ç­”: /posts/98d20436/
    âš¡ï¸ è¿›é˜¶æ•™ç¨‹: /posts/4073eda/
    âœ¨ æ›´æ–°æ—¥å¿—: /posts/198a4240/
  ç•™è¨€æ¿: /messageboard/ || fas fa-comment-dots
  è¯­è¨€||fas fa-language:
    English: /en/ || fas fa-e
    ä¸­æ–‡: / || fas fa-c


# A simple 404 page
error_404:
  enable: true
  subtitle: 'é é¢æ²’æœ‰æ‰¾åˆ°'
  background: https://oss.012700.xyz/butterfly/2024/10/butterfly-404.png


# --------------------------------------
# Bottom right button
# --------------------------------------

# The distance between the bottom right button and the bottom (default unit: px)
rightside_bottom:

# Conversion between Traditional and Simplified Chinese
translate:
  enable: true
  # The text of a button
  default: ç°¡
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chineseï¼‰
  defaultEncoding: 1
  # Time delay
  translateDelay: 0
  # The text of the button when the language is Simplified Chinese
  msgToTraditionalChinese: 'ç¹'
  # The text of the button when the language is Traditional Chinese
  msgToSimplifiedChinese: 'ç°¡'

# Snackbar - Toast Notification
# https://github.com/polonel/SnackBar
# position: top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: false
  position: bottom-left
  # The background color of Toast Notification in light mode and dark mode
  bg_light: '#49b1f5'
  bg_dark: '#1f1f1f'

## abbrlink config
# abbrlink:
#   alg: crc32      #support crc16(default) and crc32 è¿›åˆ¶
#   rep: hex        #support dec(default) and hex  ç®—æ³•
#   drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
#   ## Generate categories from directory-tree
#   ## depth: the max_depth of directory-tree you want to generate, should > 0
#   auto_category:
#      enable: true  #true(default)
#      depth:        #3(default)
#      over_write: false 
#   auto_title: false #enable auto title, it can auto fill the title by path
#   auto_date: false #enable auto date, it can auto fill the date by time today
#   force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink.
